### ISSUE TITLE
MyData fails to upload data of a MyTardis user whose name is listed after a non-MyTardis user

### ISSUE THREAD

**Issue by iiman** [mytardis/mytardis-app-mydata#3]
Hi,

I will use a scenario to explain the issue.

Given:
- DATA_DIRECTORY is a path to datasets
- MyData is configured to have a folder structure of "Username/Dataset". This folder structure resides under $DATA_DIRECTORY
- The users that are listed under $DATA_DIRECTORY are James, Martha, Peter and Richard.
- James, Martha and Richard are MyTardis users but Peter is not.

Result:
- MyData will upload datasets of James and Martha. But it will not upload Richard's datasets. This is because MyData stops uploading as soon as it finds a non-MyTardis user, which is Peter in this scenario. 

Suggestion:
MyData should ignore non-MyTardis users and continue uploading datasets of MyTardis users. This is important especially if $DATA_DIRECTORY is a network drive that is accessed by both MyTardis and non-MyTardis users.

Cheers,

**Comment by wettenhj** [comment]
This issue was moved to mytardis/mydata#25

**Comment by wettenhj** [comment]
Should be fixed by this commit: https://github.com/wettenhj/mytardis-app-mydata/commit/2faeb6b2fc8787e547037904d89a860afce0d800

@iiman, can you try pulling in the latest commit from https://github.com/wettenhj/mytardis-app-mydata into your tardis/apps/mydata/ directory on your MyTardis server and then restart MyTardis (or send the parent gunicorn process a HUP signal), and let me know if this fixes the problem you reported?

**Comment by iiman** [comment]
Hi James

The problem is fixed now.

Attached is a screenshot of MyTardis Data Store that shows uploaded data
from an unknown user Jane.

Thanks
Iman

On 11 November 2015 at 13:23, James Wettenhall <notifications@github.com>
wrote:

> Should be fixed by this commit: 2faeb6b
> <https://github.com/wettenhj/mytardis-app-mydata/commit/2faeb6b2fc8787e547037904d89a860afce0d800>
>
> @iiman <https://github.com/iiman>, can you try pulling in the latest
> commit from https://github.com/wettenhj/mytardis-app-mydata into your
> tardis/apps/mydata/ directory on your MyTardis server and then restart
> MyTardis (or send the parent gunicorn process a HUP signal), and let me
> know if this fixes the problem you reported?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wettenhj/mytardis-app-mydata/issues/3#issuecomment-155635134>
> .
>



-- 
Iman I. Yusuf, PhD
Software Engineer and Research Academic, E-Research Office
Research & Innovation Portfolio
RMIT University, Melbourne, Australia

Phone:     +61 3 9925 0114
Location:  96.1.5
<https://plus.google.com/100700838391826629572/about>
<http://au.linkedin.com/in/imanyusuf>  <https://twitter.com/iimanyusuf>
