### ISSUE TITLE
Ignoring data from unknown users

### ISSUE THREAD

**Issue by iiman** [mytardis/mytardis-app-mydata#4]
Hi James

Is there a way to ignore data from unknown users? The current Mydata version uploads any data regardless of the user's status. We have a use case where ignoring data from unknown users is highly desirable.

Thanks

**Comment by wettenhj** [comment]
No, there's no way yet.

There is a concept of "filters", but they are rather simple, e.g. match all folders matching a wildcard pattern like "\*dataset\*".  The Filters of the Settings dialog could have an "Excludes" section I suppose, but I'd have to think about how long it would take to implement.

**Comment by iiman** [comment]
I am working on an app that will help to injest data from known users only. After it is completed, I could merge this app to mydata.  I will update u once the app is completed

Cheers

**Comment by wettenhj** [comment]
Thanks for letting me know.  I'll be interested to see your design and implementation.

I can certainly see value in having a checkbox telling MyData to only include known users, and/or an "excludes" filter to exclude folders at the user level matching certain patterns.

The only danger of filters is that users can forget that filters are turned on and accidentally exclude valuable data from the uploads.  Perhaps this can be mitigated by having MyData automatically upload its settings to the server, so the MyTardis Admins can see which MyData instances have filters turned on.  Then when you get a HelpDesk query asking why a folder didn't upload, you could check whether filters are turned on.
